# Generated by Django 3.1.4 on 2021-05-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210507_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='junior',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='mid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='senior',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='countdown',
            field=models.DateTimeField(),
        ),
    ]
